config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: 'pages#home'
  devise_scope :user do
    root to: 'assets#index'
  end

  resources :assets, only: :index do
    resources :bonds, only: :index
    resources :cashes, only: %i[index]
    resources :properties, only: %i[index]
    resources :stocks, only: %i[index]
    resources :cash_deposits, only: %i[index]
    resources :cash_withdrawals, only: %i[index]
  end

  resources :bonds, except: %i[index]
  resources :cashes, except: %i[index]
  resources :properties, except: %i[index]
  resources :stocks, except: %i[index]
  resources :cash_deposits, except: %i[index edit update show]
  resources :cash_withdrawals, except: %i[index edit update show]
  resources :payouts, only: :index
end

app/views/shared/_back.html.erb
<div class="mt-3">
  <%= link_to assets_path, class:"text-decoration-none" do %>
    <div class="d-flex">
      <i class="fas fa-chevron-left mt-1 mr-2"></i>
      <h4>Back</h4>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon pb-0">
  <%= link_to assets_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png",style:"object-fit:cover; width:40px; height:40px; border-radius:50%" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <!-- <li class="nav-item">
          <%#= link_to "Messages", "#", class: "nav-link" %>
        </li> -->
        <li class="nav-item dropdown">
          <%= image_tag "img.jpg", class: "avatar-large dropdown-toggle",style:"object-fit:cover; width:40px; height:40px;", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <!-- <i class="far fa-user-circle avatar dropdown-toggle" id= "navbarDropdown" toggle="dropdown" aria-haspopup= true aria-expanded= false ></i> -->
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>