config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: 'pages#home'
  devise_scope :user do
    root to: 'assets#index'
  end

  resources :assets, only: :index do
    resources :bonds, only: :index
    resources :cashes, only: %i[index]
    resources :properties, only: %i[index]
    resources :stocks, only: %i[index]
    resources :cash_deposits, only: %i[index]
    resources :cash_withdrawals, only: %i[index]
  end

  resources :bonds, except: %i[index]
  resources :cashes, except: %i[index]
  resources :properties, except: %i[index]
  resources :stocks, except: %i[index]
  resources :cash_deposits, except: %i[index edit update show]
  resources :cash_withdrawals, except: %i[index edit update show]
  resources :payouts, only: :index
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :user

  has_one :cash
  has_many :bonds
  has_many :payouts, through: :bonds
  has_many :properties
  has_many :stocks
  has_many :cash_deposits, through: :cash
  has_many :cash_withdrawals, through: :cash

  monetize :total_value_cents
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  def index
    Asset.create(user: current_user, total_value_cents: 0) unless current_user.asset.present?
    @asset = current_user.asset
    Cash.create(asset: @asset) unless current_user.cash.present?
    @new_bond = Bond.new
    @new_property = Property.new
    @new_stock = Stock.new
    @new_cash = Cash.new
  end
end

app/views/assets/_new_bond.html.erb
<%= simple_form_for @new_bond, url: bonds_path, html: { class: "needs-validation ml-5"} do |f| %>
  <div class="form-group">
     <%= f.input :amount, input_html: { class:"form-control"}, required: true %>
    <div class="valid-feedback">Valid.</div>
    <div class="invalid-feedback">Please fill out this field.</div>
  </div>
  <div class="row">
    <div class="col-6">
      <div class="form-group">
        <%= f.input :terms, collection: %w[monthly quarterly] , include_blank:" Choose Term " %>
        <div class="valid-feedback">Valid.</div>
        <div class="invalid-feedback">Please fill out this field.</div>
      </div>
    </div>
    <div class="col-6">
      <div class="form-group">
        <%= f.input :period, collection: 1..10, selected: 3, hint: "Period in years" %>
        <div class="valid-feedback">Valid.</div>
        <div class="invalid-feedback">Please fill out this field.</div>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.input :start_date %>
    <div class="valid-feedback">Valid.</div>
    <div class="invalid-feedback">Please fill out this field.</div>
  </div>
  <div class="form-group">
    <%= f.input :end_date %>
    <div class="valid-feedback">Valid.</div>
    <div class="invalid-feedback">Please fill out this field.</div>
  </div>
  <div class="form-group">
    <%= f.input :interest_rate  %>
    <div class="valid-feedback">Valid.</div>
    <div class="invalid-feedback">Please fill out this field.</div>
  </div>
  <%= f.hidden_field 'asset_id', value: @asset.id %>
  <%= f.button :submit, class:"btn btn-primary" %>
<% end %>



<script>
// Disable form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Get the forms we want to add validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>

app/views/assets/_new_deposit.html.erb
<!-- <%#= simple_form_for @new_cash, url: cashes_path, html: { class: "needs-validation ml-5"} do |f| %>
  <div class="form-group">
     <%#= f.input :amount, input_html: { class:"form-control"}, required: true %>
    <div class="valid-feedback">Valid.</div>
    <div class="invalid-feedback">Please fill out this field.</div>
  </div>
  <div class="form-group">
    <%#= f.input :sources, input_html: { class:"form-control"}, required: true %>
    <div class="valid-feedback">Valid.</div>
    <div class="invalid-feedback">Please fill out this field.</div>
  </div>

  <%#= f.hidden_field 'asset_id', value: @asset.id %>
  <%#= f.button :submit, class:"btn btn-primary" %>
<%# end %>



<script>
// Disable form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Get the forms we want to add validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>

 -->

app/views/assets/_new_property.html.erb
<%= simple_form_for @new_property, url: properties_path, html: { class: "needs-validation ml-5"} do |f| %>
  <div class="form-group">
     <%= f.input :value, input_html: { class:"form-control"}, required: true %>
    <div class="valid-feedback">Valid.</div>
    <div class="invalid-feedback">Please fill out this field.</div>
  </div>
  <div class="form-group">
    <%= f.input :location %>
    <div class="valid-feedback">Valid.</div>
    <div class="invalid-feedback">Please fill out this field.</div>
  </div>
  <div class="row">
    <div class="col-6">
      <div class="form-group">
        <%= f.input :rent_amount, input_html: { class:"form-control"}, required: true %>
        <div class="valid-feedback">Valid.</div>
        <div class="invalid-feedback">Please fill out this field.</div>
      </div>
    </div>
    <div class="col-6">
      <div class="form-group">
        <%= f.input :rented %>
        <div class="valid-feedback">Valid.</div>
        <div class="invalid-feedback">Please fill out this field.</div>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.input :description %>
    <div class="valid-feedback">Valid.</div>
    <div class="invalid-feedback">Please fill out this field.</div>
  </div>

  <%= f.hidden_field 'asset_id', value: @asset.id %>
  <%= f.button :submit, class:"btn btn-primary" %>
<% end %>



<script>
// Disable form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Get the forms we want to add validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>

app/views/assets/_new_stock.html.erb
<%= simple_form_for @new_stock, url: stocks_path, html: { class: "needs-validation ml-5"} do |f| %>
  <div class="form-group">
     <%= f.input :instrument, input_html: { class:"form-control"}, required: true %>
    <div class="valid-feedback">Valid.</div>
    <div class="invalid-feedback">Please fill out this field.</div>
  </div>
  <div class="form-group">
    <%= f.input :symbol %>
    <div class="valid-feedback">Valid.</div>
    <div class="invalid-feedback">Please fill out this field.</div>
  </div>
  <div class="form-group">
    <%= f.input :position %>
    <div class="valid-feedback">Valid.</div>
    <div class="invalid-feedback">Please fill out this field.</div>
  </div>
  <div class="form-group">
    <%= f.input :average_price %>
    <div class="valid-feedback">Valid.</div>
    <div class="invalid-feedback">Please fill out this field.</div>
  </div>

  <%= f.hidden_field 'asset_id', value: @asset.id %>
  <%= f.button :submit, class:"btn btn-primary" %>
<% end %>



<script>
// Disable form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Get the forms we want to add validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>

app/views/assets/index.html.erb
<div class="container">

  <ul class="nav nav-pills mt-5">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="pill" href="#assets">Assets</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="pill" href="#addNew">New asset</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="pill" href="#menu2">Menu 2</a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div class="tab-pane container active mt-4" id="assets">
      <div class="d-flex flex-wrap mt-4 gap-4 justify-content-center">

        <%= link_to asset_bonds_path(@asset), class:"text-decoration-none" do %>
          <div class="card text-center m-2 " style="width: 11rem;border-radius: 30px;">
            <div class="card-body ">
              <h5 class="card-title">Bonds</h5>
              <i class="fas fa-file-invoice-dollar" style="font-size: 5vh;color: gray;"></i>
            </div>
          </div>
        <% end %>

        <%= link_to asset_cashes_path(@asset), class:"text-decoration-none" do %>
          <div class="card text-center m-2"  style="width: 11rem;border-radius: 30px;">
            <div class="card-body ">
              <h5 class="card-title">Cash</h5>
              <i class="fas fa-money-bill-wave-alt" style="font-size: 5vh;color: gray;"></i>
            </div>
          </div>
        <% end %>
        <%= link_to asset_properties_path(@asset), class:"text-decoration-none" do %>
          <div class="card text-center m-2"  style="width: 11rem;border-radius: 30px;">
            <div class="card-body ">
              <h5 class="card-title">Properties</h5>
              <i class="far fa-building" style="font-size: 5vh;color: gray;"></i>
            </div>
          </div>
        <% end %>
        <%= link_to asset_stocks_path(@asset), class:"text-decoration-none" do %>
          <div class="card text-center m-2"  style="width: 11rem;border-radius: 30px;">
            <div class="card-body ">
              <h5 class="card-title">Stocks</h5>
              <i class="fas fa-chart-line" style="font-size: 5vh;color: gray;"></i>
            </div>
          </div>
        <% end %>

      </div>
    </div>

    <div class="tab-pane container fade" id="addNew">
      <div class="d-flex align-items-start mt-5">
        <div class="nav flex-column nav-pills me-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">
          <a class="nav-link active" id="v-pills-home-tab" data-bs-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">New bond</a>
          <a class="nav-link mt-3" id="v-pills-profile-tab" data-bs-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">New deposit</a>
          <a class="nav-link mt-3" id="v-pills-messages-tab" data-bs-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">New property</a>
          <a class="nav-link mt-3" id="v-pills-settings-tab" data-bs-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">New Stock</a>
        </div>
        <div class="tab-content" id="v-pills-tabContent">
          <div class="tab-pane fade show active vw-61" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
            <%= render 'new_bond' %>
          </div>
          <div class="tab-pane fade vw-61" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
             <%= render 'new_deposit' %>
          </div>
          <div class="tab-pane fade vw-61" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
             <%= render 'new_property' %>
          </div>
          <div class="tab-pane fade vw-61" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
             <%= render 'new_stock' %>
          </div>
        </div>
      </div>
    </div>

    <div class="tab-pane container fade" id="menu2">
      <!-- whatever we pass inside menu2 tab -->
    </div>
  </div>



</div>
<style>
  .vw-61{
    width: 61vw !important;
  }
  .card:hover {
    animation: mymove 3s infinite;
  }

  @keyframes mymove {

    50% {box-shadow: rgba(0, 0, 0, 0.4) 0px 30px 90px;}
  }
</style>