config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: 'pages#home'
  devise_scope :user do
    root to: 'assets#index'
  end

  resources :assets, only: :index do
    resources :bonds, only: :index
    resources :cashes, only: %i[index]
    resources :properties, only: %i[index]
    resources :stocks, only: %i[index]
    resources :cash_deposits, only: %i[index]
    resources :cash_withdrawals, only: %i[index]
  end

  resources :bonds, except: %i[index]
  resources :cashes, except: %i[index]
  resources :properties, except: %i[index]
  resources :stocks, except: %i[index]
  resources :cash_deposits, except: %i[index edit update show]
  resources :cash_withdrawals, except: %i[index edit update show]
  resources :payouts, only: :index
end

app/models/bond.rb
class Bond < ApplicationRecord
  belongs_to :asset
  has_many :payouts
  monetize :amount_cents
  monetize :annual_return_cents
  monetize :monthly_return_cents
  monetize :quarterly_return_cents
  monetize :compound_cents

  enum terms: {
    monthly: 'monthly',
    quarterly: 'quarterly'
  }

  validates :amount_cents, presence: true
  validates :interest_rate, presence: true, numericality: true

  validate :start_date_cannot_be_greater_than_end_date

  def start_date_cannot_be_greater_than_end_date
    errors.add(start_date, "End date must be greater than start date") if start_date >= end_date
  end

  def job
    # raise
    NotifyUserJob.perform_now(current_user)
  end

  private
end

app/controllers/bonds_controller.rb
class BondsController < ApplicationController
  before_action :set_bond, only: %i[show edit update destroy]
  # before_action :job, only: :index

  def index
    # raise
    if params[:query].present?
      # sql_query = "model @@ :query OR address @@ :query OR description @@ :query"
      @bonds = Bond.where(sql_query, query: "%#{params[:query]}%")
    else
      @bonds = current_user.bonds.order(created_at: :desc)
    end
    @total = @bonds.sum(:amount_cents) / 100
    @new_bond = Bond.new
  end

  def show
    authorize @bond
  end

  # def new
  #   @bond = Bond.new
  #   authorize @bond
  # end

  def create
    @bond = Bond.new(bond_params)
    set_period
    add_returns
    authorize @bond
    if @bond.save
      redirect_to asset_bonds_path(@bond.asset), notice: "Your bond has been created"
    else
      redirect_to asset_bonds_path(@bond.asset), alert: "Something went wrong "
    end
  end

  def edit
    authorize @bond
  end

  def update
    raise
    authorize @bond
    if @bond.update(bond_params)
      redirect_to @bond, notice: "Your bond details have been updated"
    else
      render :edit
    end
  end

  def destroy
    asset = @bond.asset
    authorize @bond
    @bond.payouts.destroy_all
    @bond.destroy
    redirect_to asset_bonds_path(asset), notice: "Your bond has been deleted"
  end

  private

  def add_returns
    @bond.annual_return_cents = ((@bond.interest_rate / 100) * @bond.amount_cents).to_i
    if @bond.terms == "monthly"
      @bond.monthly_return_cents = (@bond.annual_return_cents / 12)
      @bond.compound_cents = (@bond.amount_cents * (1 + (@bond.interest_rate / 100) / 12)**(12 * @bond.period)).to_i
      # creating payouts
      counter = 1
      total_payouts = @bond.period * 12
      total_payouts.times do
        Payout.create(
          amount_cents: @bond.monthly_return_cents,
          bond: @bond,
          payout_date: @bond.start_date + counter.months
        )
        counter += 1
      end
    else
      @bond.quarterly_return_cents = (@bond.annual_return_cents / 4)
      @bond.compound_cents = (@bond.amount_cents * (1 + (@bond.interest_rate / 100) / 4)**(4 * @bond.period)).to_i
      # creating payouts
      payouts = [3]
      total_payouts_quarterly = @bond.period * 4
      (total_payouts_quarterly - 1).times do
        payouts << (payouts.last + 3)
      end
      payouts.each do |payout|
        Payout.create(
          amount_cents: @bond.quarterly_return_cents,
          bond: @bond,
          payout_date: @bond.start_date + payout.months
        )
      end
    end
  end

  def set_period
    @bond.period = ((@bond.end_date - @bond.start_date) / 365).floor
  end

  def bond_params
    params.require(:bond).permit(:terms, :amount, :start_date, :end_date, :asset_id, :interest_rate, :period)
  end

  def set_bond
    @bond = Bond.find(params[:id])
  end
end

app/views/bonds/_new_bond_modal.html.erb
<div class="modal fade" id="newBondModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg" role="document">
    <div class="modal-content" style="border-radius: 2rem;">

      <div class="modal-header mx-3">
        <h5 class="modal-title" id="exampleModalLabel">Creating new Bond</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="container mt-3 bg-white">
          <div class="row">
            <div class="col-8 mx-auto">
              <%= simple_form_for new_bond, url: bonds_path do |f| %>
                <div class="row g-3">
                  <div class="col-6">
                    <%= f.input :amount %>
                  </div>
                  <div class="col-6 ">
                    <%= f.input :terms, collection: %w[monthly quarterly] , include_blank:" Choose Term " %>
                  </div>
                </div>
                 <div>
                   <%= f.input :start_date %>
                   <%= f.input :end_date %>
                   <%= f.input :interest_rate  %>
                   <%= f.hidden_field 'user_id', value: current_user.id %>
                 </div>
            </div>
          </div>
        </div>
      </div>

      <div class="modal-footer mx-3">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
         <%= f.button :submit, class:"btn btn-primary" %>
         <% end %>
      </div>

    </div>
  </div>
</div>

app/views/bonds/_update_bond_modal.html.erb
<!-- update bond data -->

<div class="modal fade" id="updatebondModal<%= bond.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg" role="document">
    <div class="modal-content" style="border-radius: 2rem;">

      <div class="modal-header mx-3">
        <h5 class="modal-title" id="exampleModalLabel">Update Bond# <%= bond.id %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="container mt-3 bg-white">
          <div class="row">
            <div class="col-8 mx-auto">
              <%= simple_form_for bond, url: bond_path(bond.id) do |f| %>
                <div class="row g-3">
                  <div class="col-6">
                    <%= f.input :amount, html: {id:"#{bond.id}"} %>
                  </div>
                  <div class="col-6 ">
                    <%= f.input :terms, collection: %w[monthly quarterly] , include_blank:" Choose Term " %>
                  </div>
                </div>
                 <div>
                   <%= f.input :start_date %>
                   <%= f.input :end_date %>
                   <%= f.input :interest_rate  %>
                   <%= f.hidden_field 'user_id', value: current_user.id %>
                 </div>
            </div>
          </div>
        </div>
      </div>

      <div class="modal-footer mx-3">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
         <%= f.button :submit, class:"btn btn-primary" %>
         <% end %>
      </div>

    </div>
  </div>
</div>

app/views/bonds/index.html.erb
<div class="container">
  <%= render 'shared/back' %>
<div class="d-flex justify-content-between mt-2">
  <h1>Bonds</h1>
  <div class="h-50">
    <%= link_to 'Bonds payouts schedule', payouts_path, class:"btn btn-outline-primary mr-3" %>
    <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#newBondModal">Add new Bond</button>
  </div>
</div>
<div class="d-flex">
  <h3 id="totalBonds">All bonds total = <%= humanized_money(@total) %></h3>
  <i id="see" class="fas fa-eye mt-2 ml-3" style="color: black;font-size: 1rem;"></i>

</div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col" class="w-1vw">#</th>
        <th scope="col" class="w-1vw">Start date</th>
        <th scope="col" class="w-1vw">End date</th>
        <th scope="col" class="w-1vw">Interest rate</th>
        <th scope="col" class="w-1vw">Amount</th>
        <th scope="col" class="w-1vw">Duration</th>
        <th scope="col" class="w-1vw">Term</th>
        <th scope="col" class="w-1vw">Term return</th>
        <th scope="col" class="w-1vw">Annual return</th>
        <th scope="col" class="w-1vw">Defaulted Value</th>
        <th scope="col" class="w-1vw">Compounded Value</th>
      </tr>
    </thead>
    <tbody>
        <% counter = 1 %>
        <% @bonds.each do |bond| %>
      <tr>
          <th scope="row"><%= counter %></th>
          <td class="w-1vw"><%= bond.start_date %></td>
          <td class="w-1vw"><%= bond.end_date %></td>
          <td class="w-1vw"><%= bond.interest_rate %>%</td>
          <td class="w-1vw"><%= humanized_money(bond.amount) %></td>
          <td class="w-1vw"><%= pluralize(bond.period, "year") %></td>
          <% if bond.terms == "monthly" %>
            <td class="w-1vw"><span class="badge rounded-pill bg-primary" style="color: white;">M</span></td>
            <td class="w-1vw"><%= humanized_money(bond.monthly_return)%></td>
          <% else %>
            <td class="w-1vw"><span class="badge rounded-pill bg-success">Q</span></td>
            <td class="w-1vw"><%= humanized_money(bond.quarterly_return)%></td>
          <% end %>
          <td class="w-1vw"><%= humanized_money(bond.annual_return) %></td>
          <% normal_retun = ((bond.annual_return_cents * bond.period) / 100) + (bond.amount_cents / 100) %>
          <td class="w-1vw"><%= humanized_money(normal_retun) %></td>
          <td class="w-1vw"><%= humanized_money(bond.compound) %></td>
          <td class="w-1vw" class=" pb-0">
            <p class="card-text d-flex flex-row-reverse justify-content-between">
              <%= link_to bond_path(bond.id), method: :delete, data: { confirm: "Are you sure you want to delete this bond?", disable_with: "Processing..." } do %>
                <i class="far fa-trash-alt" style="color: #ec524b;"></i>
              <% end %>
              <button class="m-0" type="button" data-toggle="modal" data-target="#updatebondModal<%= bond.id %>">
                <i class="far fa-edit mx-3" style="color: gray;"></i>
              </button>
            </p>
          </td>
          <%= render partial: 'update_bond_modal', locals:{ bond: bond } %>
      </tr>
          <% counter += 1 %>
        <% end %>
    </tbody>
  </table>
</div>
<%#= render partial: 'new_bond_modal', locals:{ new_bond: @new_bond } %>

<script>
  const total = document.getElementById('totalBonds')
  const visible = document.getElementById('see')

  visible.addEventListener('click',(event) => {
    if (total.innerHTML === "All bonds total = XXXXXXX") {
        total.innerHTML = "All bonds total = <%= humanized_money(@total) %>";
      } else {
        total.innerHTML = "All bonds total = XXXXXXX";
      };
    visible.classList.toggle("fa-eye-slash");
  });

</script>
<style>
  .w-1vw{
    width: 1.5vw;
  }
</style>