config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: 'pages#home'
  devise_scope :user do
    root to: 'assets#index'
  end

  resources :assets, only: :index do
    resources :bonds, only: :index
    resources :cashes, only: %i[index]
    resources :properties, only: %i[index]
    resources :stocks, only: %i[index]
    resources :cash_deposits, only: %i[index]
    resources :cash_withdrawals, only: %i[index]
  end

  resources :bonds, except: %i[index]
  resources :cashes, except: %i[index]
  resources :properties, except: %i[index]
  resources :stocks, except: %i[index]
  resources :cash_deposits, except: %i[index edit update show]
  resources :cash_withdrawals, except: %i[index edit update show]
  resources :payouts, only: :index
end

app/models/cash_withdrawal.rb
class CashWithdrawal < ApplicationRecord
  belongs_to :cash

  monetize :amount_cents
end

app/controllers/cash_withdrawals_controller.rb
class CashWithdrawalsController < ApplicationController
  def new
  end

  def create
    @cash_withdrawal = CashWithdrawal.new(cash_withdrawal_params)
    @cash = @cash_withdrawal.cash
    @cash.update(amount_cents: @cash.amount_cents - @cash_withdrawal.amount_cents)
    authorize @cash_withdrawal
    if @cash_withdrawal.save
      create_cash_transaction
      redirect_to asset_cashes_path(@cash.asset), notice: "Your withdrawal has been made"
    else
      redirect_to asset_cashes_path(@cash.asset), notice: "Your cash withdrawal has NOT been made"
    end
  end

  def destroy
  end

  def index
  end

  private

  def cash_withdrawal_params
    params.require(:cash_withdrawal).permit(:reason, :amount, :cash_id)
  end

  def create_cash_transaction
    CashTransaction.create(
      user: current_user,
      amount_cents: @cash_withdrawal.amount_cents,
      action: "withdraw",
      details: "For #{@cash_withdrawal.reason}"
    )
  end
end

app/views/cash_withdrawals/_new_cash_withdrawal_modal.html.erb
<div class="modal fade" id="cashWithdrawalModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg" role="document">
    <div class="modal-content" style="border-radius: 2rem;">

      <div class="modal-header mx-3">
        <h5 class="modal-title" id="exampleModalLabel">Withdrawal</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="container mt-3 bg-white">
          <div class="row">
            <div class="col-8 mx-auto">
              <%= simple_form_for new_withdrawal, url: cash_withdrawals_path do |f| %>
                <div class="row g-3">
                  <div class="col-12">
                    <%= f.input :amount %>
                  </div>
                  <div class="col-12 ">
                    <%= f.input :reason %>
                    <%= f.hidden_field 'cash_id', value: current_user.cash.id %>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>

      <div class="modal-footer mx-3">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
         <%= f.button :submit, class:"btn btn-primary" %>
         <% end %>
      </div>

    </div>
  </div>
</div>

app/views/cash_withdrawals/index.html.erb
<h1>CashWithdrawals#index</h1>
<p>Find me in app/views/cash_withdrawals/index.html.erb</p>

app/views/cash_withdrawals/new.html.erb
<h1>CashWithdrawals#new</h1>
<p>Find me in app/views/cash_withdrawals/new.html.erb</p>